# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

# - task: UseDotNet@2
#   inputs:
#     packageType: 'sdk'
#     version: '5.0.x'
#     performMultiLevelLookup: true

- script: dotnet build ./Milestone3 --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
# - task: DotNetCoreCLI@2
#   displayName: Build
#   inputs:
#     command: build
#     projects: './12142020_MvcRpsDemo/12142020_MvcRpsDemo.sln'
#     arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: './12142020_MvcRpsDemo.Tests/12142020_MvcRpsDemo.Tests.csproj'
    arguments: --configuration $(buildConfiguration)' --collect "Code Coverage"

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'batch12142020'
    organization: 'batch12142020'
    scannerMode: 'MSBuild'
    projectKey: 'batch12142020_12142020PipeLineDemo'
    projectName: '12142020PipeLineDemo'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Agent.TempDirectory)/*/coburtura/coverage.xml'



- task: SonarCloudAnalyze@1
  displayName: run code analysis

- task: SonarCloudPublish@1
  displayName: publish code analysis

# - task: DotNetCoreCLI@2
#   displayName: 'dotnet publish and zip'
#   inputs:
#     command: 'publish'
#     publishWebProjects: true
#     zipAfterPublish: true











# - task: SonarCloudPrepare@1
#   inputs:
#     SonarCloud: 'batch12142020'
#     organization: 'batch12142020'
#     scannerMode: 'MSBuild'
#     projectKey: 'batch12142020_12142020PipeLineDemo'
#     projectName: '12142020PipeLineDemo'


# do this after your tests have run
# - script: dotnet test ./12142020_MvcRpsDemo.sln --logger trx
# - task: PublishTestResults@2
#   condition: succeededOrFailed()
#   inputs:
#     testRunner: VSTest
#     testResultsFiles: '**/*.trx'



















